pipeline {
    agent any  // Usa cualquier nodo disponible para ejecutar el pipeline

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'  // La imagen Docker que usarás en esta etapa
                    args '-v /var/run/docker.sock:/var/run/docker.sock'  // Montaje de Docker socket, si es necesario
                }
            }
            steps {
                script {
                    // Aquí se compilan los archivos Python, adaptado a tu caso
                    sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                }
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'  // Imagen Docker para ejecutar las pruebas
                    args '-v /var/run/docker.sock:/var/run/docker.sock'  // Montaje de Docker socket
                }
            }
            steps {
                script {
                    // Ejecuta las pruebas con pytest
                    sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
                }
            }
            post {
                always {
                    junit '**/test-reports/*.xml'  // Publica los resultados de las pruebas
                }
            }
        }

        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'  // Imagen Docker para empaquetar el ejecutable
                    args '-v /var/run/docker.sock:/var/run/docker.sock'  // Montaje de Docker socket
                }
            }
            steps {
                script {
                    // Empaqueta la aplicación Python en un archivo ejecutable
                    sh 'pyinstaller --onefile sources/add2vals.py'
                }
            }
            post {
                success {
                    // Archiva el artefacto generado
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
